version: '3'

services:
  mysql:
    image: mysql:8.0 # versión mínima obligatoria para moodle 4.5.2
    container_name: mysql
    hostname: moodle
    restart: unless-stopped
    volumes:
      - db-scripts:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: R00tPaSsWoRd!!!
      MYSQL_USER: moodle
      MYSQL_PASSWORD: M0oDleP@sSw0rD
      MYSQL_DATABASE: moodle

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: R00tPaSsWoRd!!!
      PMA_HOST: mysql
    depends_on:
      - mysql

  apache:
    build: apache/
    container_name: apache
    hostname: apache
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - www-html:/var/www/html/
      - db-scripts:/mysql-scripts/

  php:
    build: php/
    container_name: php
    hostname: php
    restart: unless-stopped
    volumes:
      - www-html:/var/www/html/

  moodle:
    image: bitnami/moodle:4.5.2
    container_name: moodle
    hostname: moodle
    restart: unless-stopped
    ports:
      -  8080:8080
    depends_on:
      - mysql
    environment:
      MOODLE_DATABASE_TYPE: mysqli
      MOODLE_DATABASE_HOST: mysql
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: M0oDleP@sSw0rD
      MOODLE_LANG: es
      MOODLE_USERNAME: admin
      MOODLE_PASSWORD: AdminBirt@6
      MOODLE_SITE_NAME: Moodle Birt

volumes:
  www-html:
  db-scripts:
